-- ============================================================
-- Measure: MoM Night Distance % Change
-- Table:   VanRakshak_MasterDataset
-- Author:  Inderjot Singh Matharoo
-- Purpose: Calculates month-over-month percentage change in
--          total patrol distance for night patrols
-- Used in: Night Patrolling Summary, Night Data Extractor
-- ============================================================

MoM Night Distance % Change =
VAR CurrentMonth =
    CALCULATE(
        SUM(vw_sb_patrol_night[total_distance]),
        DATESMTD(vw_sb_dim_date[calendar_date])
    )
VAR LastMonth =
    CALCULATE(
        SUM(vw_sb_patrol_night[total_distance]),
        DATEADD(
            DATESMTD(vw_sb_dim_date[calendar_date]),
            -1,
            MONTH
        )
    )
RETURN
    DIVIDE(CurrentMonth - LastMonth, LastMonth, 0)

-- ============================================================
-- Notes:
-- • Mirror of MoM Distance % Change but for night patrol data
-- • Uses vw_sb_patrol_night instead of vw_sb_patrol_all
-- • Returns 0 when no prior month data exists
-- • Format as Percentage with 1 decimal place
-- ============================================================
